apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easymaid-sites-pvc
  namespace: easymaid
  annotations:
    numberOfReplicas: "2"
  labels:
    app.kubernetes.io/name: easymaid
    app.kubernetes.io/part-of: easy-maid-service
    app.kubernetes.io/component: sites
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
